### ISSUE TITLE
Test evaluating network with inputs

### ISSUE THREAD

**Issue by drewbutlerbb4** [drewbutlerbb4/Project-Plutus#11]

**Comment by drewbutlerbb4** [comment]
Running dev_test_learn_model.py produces:

Traceback (most recent call last):
  File "C:/Users/Andrew Butler/PycharmProjects/MarketEvalTests/dev_test_learn_model.py", line 22, in <module>
    neat_model.create_population(False)
  File "C:\Users\Andrew Butler\PycharmProjects\project-plutus\NEAT\NEAT\learn_model.py", line 1543, in create_population
    self.mutate(new_genome)
  File "C:\Users\Andrew Butler\PycharmProjects\project-plutus\NEAT\NEAT\learn_model.py", line 1256, in mutate
    mutation(genome)
  File "C:\Users\Andrew Butler\PycharmProjects\project-plutus\NEAT\NEAT\learn_model.py", line 1371, in mutate_bias
    random_node = genome.topological_order[random_num]
IndexError: list index out of range

**Comment by drewbutlerbb4** [comment]
There was an issue where occasionally an item in the Network.neurons list is set as an int. Unsure if this still remains or was fixed by fixing the destruction of topological ordering #14

**Comment by drewbutlerbb4** [comment]
Tested and should be fixed
